cs5

diff --git a/githook/pre-commit b/githook/pre-commit
--- a/githook/pre-commit
+++ b/githook/pre-commit
@@ -21,11 +21,13 @@ SFILES=${SFILES:-$STAGED_FILES_CMD}
 echo "Checking PHP Lint..."
 for FILE in $SFILES
 do
-    php -l -d display_errors=0 $PROJECT/$FILE
-    if [ $? != 0 ]
-    then
-	echo "Fix the error before commit."
-	exit 1
+    if [ "${FILE##*.}" = "php" ]; then
+       php -l -d display_errors=0 $PROJECT/$FILE
+       if [ $? != 0 ]
+         then
+          echo "Fix the error before commit."
+          exit 1
+       fi
     fi
     FILES="$FILES $PROJECT/$FILE"
 done
